### ISSUE TITLE
Add user middleware execution order control

### ISSUE THREAD

**Issue by operatino** [sourcejs/Source#117]
Since user could have multiple middleware plugins in one SourceJS instance, we should provide control over their execution order.

It could be done with custom configuration, containing names and order number + separation of middleware types.

First time to implement: renderers of custom templates like jade, markdown and etc. Since other middlewares relies on HTML as an input, we should provide some guaranties that they will get it, instead of jade sources.

**Comment by mik01aj** [comment]
+1

**Comment by operatino** [comment]
It's now possible to define middleware group/order and control group execution sequence. By default all middlewares (and older plugins) will be placed in `default` group. Here's the default group execution order:

```
loadGroupsOrder: [
  'request',
  'pre-html',
  'default',
  'html',
  'response'
]
```

#### Example configurations

In SourceJS core (configurable from `user/options.js`):
```
{
  core: {
    middlewares: {
        list: {
          md: {
            enabled: true,
            order: -1,
            group: 'pre-html',
            indexPath: path.join(appRoot, 'core/middlewares/md.js')
         }
      }
    }
  }
}
```

Plugin level configuration in `sourcejs-plugin-name/options.js`, will be merged on-top of defaults:
{
  order: -1,
  group: 'pre-html'
}

To override core middlewares, changing their order or replacing with alternative plugins, user will need to modify his `options.js` file. For the security reason, plugin level options can't override core middlewares or set an execution order option lower than 0 (zero).

**Comment by operatino** [comment]
@mik01aj, in your case with `sourcejs-react-md` plugin, you can suggest user to re-define core MD rendering middleware. It's not very safe, but can provide you more flexibility.

I will open new issue about improving the set-up of custom language renderers for code MD middleware.
