### ISSUE TITLE
Issue with generated urls when running node via powershell

### ISSUE THREAD

**Issue by szarouski** [sourcejs/Source#130]
When I get `api/specs/raw` json data, it contains local file paths instead or urls. I digged through the code a bit and found out why it is happening. In [file-tree/index.js](https://github.com/sourcejs/Source/blob/master/core/file-tree/index.js) there is a line:
```js
urlForJson = _specPath.replace(normalizedPathToApp, '');
```
The issue is happening when _specPath is different from normalizedPathToApp, for example when drive letter has different case:
_specPath = `c:/dev/node_projects/sourcejs/docs/auth/readme.md`
normalizedPathToApp = `C:/dev/node_projects/sourcejs`

It could happen because `var normalizedPathToApp = global.pathToApp.replace(/\\/g, '/');` and `global.pathToApp = __dirname;`. Funny enough but when node started via powershell, `__dirname` will return path with drive letter in uppercase, while when started with cmd, node will return path with lowercase... :S

So I guess there should be conversion to lowercase?

**Comment by operatino** [comment]
Hi, thanks for your report.

It's always an issue working with file paths in cross-platform environment, first the back-slashes and now different letter case. It's really strange that node fs returns different paths in this situation.

Anyway, the only solution will be normalizing the case as well, applying `toLowerCase()` in paths at `file-tree/index.js`.

I suggest you hotfixing it locally for now, and I will investigate this issue with more focus, applying the fix in one of the 0.5.x versions.

Could you please also provide the link to Windows Powershell download, and define it's version?

**Comment by szarouski** [comment]
Hi Robert, powershell was preinstalled on my windows 8.1. Here is a PS version:
```
PS C:\Users\Sergey> $PSVersionTable.PSVersion

Major  Minor  Build  Revision
-----  -----  -----  --------
4      0      -1     -1
```

**Comment by operatino** [comment]
I digged deeper into the problem and noticed that starting from Node.js 0.11.x `path.join` is changing the case of the disk name.

```
__dirname // -> C:\User\path
path.join(__dirname, 'some') // -> c:\User\path\some
```

Following my tests, it's true both for cmd and powershell on windows 8.1. Here's also a similar issue in Node.js project - https://github.com/joyent/node/issues/7031.

Since Windows is case-insensetive, then I believe lowering the disk name by default will be a stable fix.

**Comment by szarouski** [comment]
Awesome, thanks for double checking
