### ISSUE TITLE
Prepare built jsdom binaries for Node.js 0.12 (windows)

### ISSUE THREAD

**Issue by operatino** [sourcejs/Source#138]
Following the official solution for solving JSdom problems on windows https://github.com/sourcejs/Source/issues/23, we need to re-build binaries (https://github.com/mihaifm/jsdom_binaries) for node 0.12+.

**Comment by operatino** [comment]
@szarouski, as I understand, you already have experience running SourceJS with Node 0.12+ on Windows? Could you please provide the archive with built JSdom, so we could share it with other users?

Current binaries from this project https://github.com/mihaifm/jsdom_binaries does not support Node.js 0.12+.

**Comment by szarouski** [comment]
[Here you go](https://github.com/szarouski/jsdom_binaries). To make binaries I used the same versions of jsdom and contexify as currently used for source.js. I also think that it is not a big issue for Windows users to [install node-gyp dependencies](https://github.com/TooTallNate/node-gyp#installation) and let contexify build on their own machines.

**Comment by operatino** [comment]
@szarouski Thank you! I will check if they work with my testing Win environment.

**Comment by operatino** [comment]
I Verified new binaries, and they are working as expected. Updated instructions in https://github.com/sourcejs/Source/issues/23
