### ISSUE TITLE
Make port, host and base URL configurable in options.js

### ISSUE THREAD

**Issue by mik01aj** [sourcejs/Source#159]
1. Port. 
I know that setting a port is possible with the command-line `-p` option, but I'd like to have it in the config.

2. Host.
Listening on `localhost` instead of `0.0.0.0` would be useful not to have an open port to the whole world. Listening on a local IP would be useful to accept only requests from the local network (e.g. VPN).

3. Base URL.
Changing the base URL (that will be used for resources) would be useful for hosting Source in some subfolder on a host. For example with HAProxy we can redirect `my-server.com/styleguide/path` to its own `localhost:8080/path`, but for it to work it needs also all the resource URLs to be correct. This is relatively high priority for my case, but I understand that this case might be not very popular :)

**Comment by operatino** [comment]
Hi,

You can use core `options.js` as a reference to what could be configured https://github.com/sourcejs/Source/blob/master/options.js

1. Port is configurable both from options and with `-p`
2. I'm not sure what you mean, it is on localhost/127.0.0.1 by default. And this is not configured on app level.
3. Hm, this is nice point, and we have similar requirement for this. I will investigate this, theoretically you can already write a custom route following Express.js API's in https://github.com/sourcejs/init/blob/master/core/routes/index.js.

Here's an example of route I've done for `bower_components` folder, for resolving `localhost:8080/bower_components` to `localhost:8080/specs/button/bower_components` - https://gist.github.com/operatino/d1b7a0f2f73ae434e90a.

**Comment by mik01aj** [comment]
> I'm not sure what you mean, it is on localhost/127.0.0.1 by default. And this is not configured on app level.

Depending on the specified host, Source would then reply only to localhost, or only to local network, or the whole world. http://stackoverflow.com/questions/20778771/what-is-the-difference-between-0-0-0-0-127-0-0-1-and-localhost

I understand you don't call [Node's `listen` function](https://nodejs.org/api/http.html#http_server_listen_port_hostname_backlog_callback) directly, but your framework (express?) should have an option to change the port.

**Comment by operatino** [comment]
Ok, I will check this out, must be not that difficult, you can expect second article to be implemented quite soon on `0.5.4-dev`.

**Comment by operatino** [comment]
Hi, 

Sorry for the delay with fixing this issue, I just returned from my vacation, and now will have spare week only for SourceJS development. You can expect 0.5.4 release with this fix in a week.

**Comment by mik01aj** [comment]
Thanks :+1:

**Comment by operatino** [comment]
I added an ability to configure everything for `server.listen` call, so now it's possible to define hostname and other arguments following the spec https://nodejs.org/api/http.html#http_server_listen_port_hostname_backlog_callback.

```
{
  core: {
    server: {
          port: 8080,
          hostname: undefined
        }
    }
}
```

There's also a cli argument available `--hostname`.

**Comment by operatino** [comment]
Returning to the last request with base-url definition. Let's discuss how it should be done, and what's the expected output. It should be possible to configure a reverse-proxy with current set-up, mirroring SourceJS style guide to `anydomain.com/some/path/`. Custom location root will proxy contents from style guide engine root, and then the server configuration must prefix all the root url cals with `anydomain.com/some/path/`.

The alternative way, without custom reverse-proxy configuration is rewriting all URLs in SourceJS output HTML both for assets and for local navigation, which is quite complicated. So I suggest solving this on server configuration level, instead of rewriting the SourceJS output

**Comment by mik01aj** [comment]
I was thinking about using a reverse proxy.
