### ISSUE TITLE
Clean code for profanity.

### ISSUE THREAD

**Issue by custa1200** [sourcejs/Source#168]
While we all know and understand what a PITA things like IE especially can be, but the generated code shouldn't contain profanities. It doesn't give a polished or professional appearance. Example I have screen-shotted below,

![screenshot 2015-08-15 16 53 09](https://cloud.githubusercontent.com/assets/161224/9287850/5da5ab68-436e-11e5-8ac8-ccb706d454e0.png)

**Comment by operatino** [comment]
That's fair, I'll clean this asap. Sorry for my colleagues attitude, seems like he was really upset with yet another browser bug.

**Comment by custa1200** [comment]
No it's completely understandable, but I think if I want to look to make this a production tool within a business it needs to be "professional" for all audiences.
