### ISSUE TITLE
Inheritance

### ISSUE THREAD

**Issue by custa1200** [sourcejs/Source#170]
What is considered the best way to handle CSS inheritance for rendered specs? I would not want to have to add font-family: x; into every single spec when it is likely to be inherited from the html/body rules but because the specs are componentized they don't include things like html/body rules. Should I just include things like my sites's  main.css file into the index.src.html file?

**Comment by operatino** [comment]
You can always link any additional resources to parent spec template `user/core/views/spec.ejs`. There you can define some `reset.css` or styles base for all the specs.

The other way, following true UI components encapsulation practices, reset styles and globals (like font size etc) should be defined per component. This will ensure that components is really stand-alone.
