### ISSUE TITLE
Externalize templates for Catalogs

### ISSUE THREAD

**Issue by mistermark** [sourcejs/Source#174]
It would be good if we can have the templates for the Catalogs as external files, and not in the JS file itself.

I now need to modify the source file `globalNav.js` to be able to modify the look of the catalog and the content displayed in there. I'd like to be able to do this on a template level in the same way as we can do with the header.

![screen shot 2015-08-21 at 11 27 57](https://cloud.githubusercontent.com/assets/960311/9405453/191a2134-47f8-11e5-8675-2c374f5453be.png)

**Comment by operatino** [comment]
Totally agree, will plan this in nearest updates

**Comment by operatino** [comment]
Done in #178
