### ISSUE TITLE
pageLimit option does not work well for navigation which using tags filering

### ISSUE THREAD

**Issue by dmitrisweb** [sourcejs/Source#175]
There are few issues related to tag filtering:

1. Project has a flat structure - all items copied into '/items' folder and for building navigation used tag filtering. Now if limit amount of items only first column will have items.

2. Auto-generated link "All specs XX" - shows total for all items, but not filtered 

<img width="702" alt="screen shot 2015-08-27 at 16 11 01" src="https://cloud.githubusercontent.com/assets/225592/9522723/71e0cc36-4cd6-11e5-81ad-762dbb2b1a8b.png">

Example:

```
<script type="text/javascript">
  define('sourceModules/inlineOptions', {
      modulesOptions : {
          globalNav : {
              pageLimit: 5
          }
      }
  });
</script>

<div class="source_subhead">
  <h1>My Collection</h1>
</div>


<div class="source_col">
  <div class="source_catalog" data-nav="/items" data-tag="widget">
    <h2 class="source_catalog_title"><a href="/collections/widgets">Widgets</a></h2>
    <p>My widgets.</p>
  </div>
</div>

<div class="source_col">
  <div class="source_catalog" data-nav="/items" data-tag="module">
    <h2 class="source_catalog_title"><a href="/collections/modules">Modules</a></h2>
    <p>My modules.</p>
  </div>
</div>

<div class="source_col">
  <div class="source_catalog" data-nav="/items" data-tag="container">
    <h2 class="source_catalog_title"><a href="/collections/containers">Containers</a></h2>
    <p>My containers.</p>
  </div>
</div>
```

**Comment by operatino** [comment]
Hi, thanks for the report. Will plan a fix in next release

**Comment by cheshirsky** [comment]
Fixed in [navigation fixes branch](https://github.com/sourcejs/Source/tree/navigation-fixes).
