### ISSUE TITLE
Allow multiple tags while filtering by tag

### ISSUE THREAD

**Issue by dmitrisweb** [sourcejs/Source#176]
info.json has
```
{
  "title": "Module Name",
  "tag": [
    "myproject",
    "module",
    "universal"
  ]
}
```
This works:
```
<div class="source_col">
  <div class="source_catalog" data-nav="/items" data-tag="module">
    <h2 class="source_catalog_title">All Modules</h2>
  </div>
</div>
```

But filtering by multiple tags does not work (comma separated, nor space separated)
```
<div class="source_col">
  <div class="source_catalog" data-nav="/items" data-tag="module,universal">
    <h2 class="source_catalog_title">Universal Modules</h2>
  </div>
</div>
```

**Comment by operatino** [comment]
Useful feature request, would be great is somebody of Backbase guys could help on getting this done in core.

**Comment by cheshirsky** [comment]
Implemented in [navigation fixes branch](https://github.com/sourcejs/Source/tree/navigation-fixes).

**Comment by operatino** [comment]
@dmitrisweb, what is the expected filter behaviour? Show specs that have both tags in the list, or 2 subsets? The current implementation by @cheshirsky checks specs that has both tags, which seems a bit wrong.

**Comment by dmitrisweb** [comment]
Spec should contain both tags to be displayed - that is correct
Like show only "Universal Modules" or show only "MyProject Modules"
filtering by 2 and more tags would be very helpful

**Comment by operatino** [comment]
Ok, @cheshirsky almost finished the PR, I've done the review already.
