### ISSUE TITLE
Optimize for Node.js 4.0 stable release

### ISSUE THREAD

**Issue by operatino** [sourcejs/Source#180]
Optimize SourceJS and it's dependencies to run in latest Node.js release 4.0 (merged with io.js).

**Comment by operatino** [comment]
Currently experiencing problems only with JSDom `contextify` dependency (io.js 3.0 and Node.js 4.0).

For easy fix, run this in SourceJS folder:

```
npm install jsdom@latest --save
```

We're investigating how to make SourceJS work both with older Node.js versions and with 4.0.

**Comment by operatino** [comment]
Version in `0.6.0-dev` branch and first nightly release (`sourcejs@0.6.0-nightly.0`) already supports Node.js 0.4.x, since JSDom is now deleted from dependencies.

**Comment by mik01aj** [comment]
+1 for this issue. Just updated my Node and noticed that it broke SourceJS.

**Comment by ndelangen** [comment]
Can we close this as soon as 0.6.0 is officially released?

**Comment by operatino** [comment]
Actually, the bug is already fixed even for 0.5.6, so we can close it already.
