### ISSUE TITLE
What command do i run to initialize user directory on windows? 

### ISSUE THREAD

**Issue by jmathur5** [sourcejs/Source#192]
The onboarding process for using SourceJS difficult for me. I'm using the quick start documentation http://sourcejs.com/docs/base/#install but no where does it mention how to auto-generate the users directory like explained in the live demo https://youtu.be/ukFeZnJjrLs?t=635 . I'm working on a Windows machine, can anyone please guide me in the right direction? 

Thanks!

**Comment by operatino** [comment]
Hi,

Sure, here's the part from installation doc:

```
git clone https://github.com/sourcejs/init.git -b npm my-sourcejs && cd my-sourcejs
npm install sourcejs@0.5.6-no-jsdom --save
npm start
```

So first you clone empty initialising project (https://github.com/sourcejs/init.git), then you install latest SourceJS version into it with `npm install sourcejs@0.5.6-no-jsdom --save`.
