### ISSUE TITLE
Global custom fields in a specs

### ISSUE THREAD

**Issue by Synopticum** [sourcejs/Source#193]
SourceJS doesn't provide an opportunity to change the URL to the master-app styles dynamicaly. 
Currently, this URL should be hardcoded in the template(s) like this:
`<link href="http://production-server.com/css/all.css" rel="stylesheet" data-source="core">`

I would like to be able to change **http://production-server** in the all specs dymanicaly, for example, after the POST request to SourceJS server. I think, it might be a global variable in the options.js. Expected result:
`<link href="<%= urlToApplication %>/css/all.css" rel="stylesheet" data-source="core">`

Also, I would like to use **urlToApplication** not only in the spec templates. I use requirejs calls in the /spec/js/initSpec.js to include an external components to my spec:

```
requirejs.config({
    baseUrl: 'http://production-server.com/js/libraries',
    paths: {
        'jquery': 'jquery-2.1.0/jquery.min',
        'underscore': 'underscore/underscore-min',
        'backbone': 'backbone/backbone-min',
        'backgrid': 'backgrid'
    },
    shim: {
        'backgrid': {
            deps: ['jquery', 'underscore', 'backbone'],
            exports: 'Backgrid'
        }
    }
});

require(['jquery', 'underscore', 'backbone', 'backgrid' ], initPage);
```

Although, of course, I could add this initialization to the spec file:

```
<script>
requirejs.config({
    baseUrl: '<%= urlToApplication %>/js/libraries',
    paths: {
    ....
</script>
```

**Comment by Synopticum** [comment]
This is temporary solution. This solution don't require a modifications of the SourceJS engine code.

1. Add this code to /user/core/app.js:

```
var fs = require('fs'),
    path = require('path'),
    server = process.argv[2],
    specsList = getDirectories(__dirname + '/../specs');

specsList.forEach(function (specName) {
    var fileName = __dirname + '/../specs/' + specName + '/info.json',
        info = require('../specs/' + specName + '/info.json');

    info.server = server;

    fs.writeFileSync(fileName, JSON.stringify(info));
});

function getDirectories(srcpath) {
    return fs.readdirSync(srcpath).filter(function(file) {
        return fs.statSync(path.join(srcpath, file)).isDirectory();
    });
}
```

2. Replace in the /user/package.json `"start": "node ./node_modules/sourcejs/app.js"` to `"start": "node ./node_modules/sourcejs/app.js $SERVER"`

3. Use `<%= info.server %>` in your spec templates like this:

```
... template markup ...

<!-- dependencies -->
<link rel="stylesheet" href="<%= info.server %>/static/js/libraries/jquery-ui/jquery-ui.css">

<script>
    requirejs.config({
        baseUrl: '<%= info.server %>/static/js/libraries',
        paths: {
            'jquery': 'jquery-2.1.0/jquery.min'
        }
    });
</script>
```

*Warning*: A content of all your /spec/info.json files will be convert to one line.

**Comment by operatino** [comment]
Hi,

Sorry for the late reply. As soon as I will have time, I will provide an official way for passing custom configuration to `info` context.

Good that you found temp solution for that, but I would actually recommend using middleware for that, without writing to each `info.json` file. You can follow this example middleware, to check how can you extend the `info` object in runtime, during the spec request https://github.com/sourcejs/sourcejs-react-docgen/blob/master/core/middleware/index.js.

If you like the solution you choose, at least you can improve it witl doing `JSON.stringify(info, null, 4)` to format the output object with proper indents.

**Comment by Synopticum** [comment]
>If you like the solution you choose, at least you can improve it witl doing JSON.stringify(info, null, 4) to format the output object with proper indents.

Sure, thank you!

**Comment by ndelangen** [comment]
Is this still something that needs fixing before the 0.6.0 release?

**Comment by operatino** [comment]
Any SourceJS middleware plugin can extend the `req.specData.info`, that would be then passed to Spec renderer. This should be enough for now, if we'll see more use cases, we can think about some way of extending info.json from options.

Pull Requests also welcome.
