### ISSUE TITLE
Bad user directory

### ISSUE THREAD

**Issue by falconx** [sourcejs/Source#195]
Running on a linux env and going through the npm install steps:
```
git clone https://github.com/sourcejs/init.git -b npm my-sourcejs && cd my-sourcejs
npm install sourcejs --save
npm start
```

Source is setting the user directory — ```global.app.get('user')``` — to:
```
/home/.../my-sourcejs/node_modules/sourcejs/user
```

I would expect it to be:
```
/home/.../my-sourcejs/user
```

**Comment by operatino** [comment]
Hi,

Is this path wrong, our you expect it to be just shorter? This is already changed in `0.6.0-dev` version, so you can try `npm i sourcejs@0.6.0-nightly.4`.

**Comment by falconx** [comment]
Hi (thanks for the quick reply),

I would have said wrong because I wouldn't wan't my user overrides inside `node_modules`. After updating the package I now see this path as my user directory:
```
/home/.../my-sourcejs
```
Which I guess is now correct? My interpretation was that user content would go under a sub-folder `user`, or whatever the value of `core.common.pathToUser` is set to.

**Comment by operatino** [comment]
We still need to re-test how `core.common.pathToUser` conf works in new version, but as you got in `0.6.0` build, the default user folder is the root of `node_modules`.

**Comment by falconx** [comment]
Got it. The installation is now working as expected. Thanks for your assistance.
