### ISSUE TITLE
Customising templates HTTP 500

### ISSUE THREAD

**Issue by mackski** [sourcejs/Source#198]
Following the documentation:

```
module.exports = {
  core: { ... },
  assets: {
    ...
    moduleOptions: {
      globalNav: {
        templates: {
          catalogHeader: _.template('<h2 class="custom-class"><%= catalogMeta.title %></h2>'),
        }
      }
    }
  }
}
```

This generates a HTTP 500 which halts execution. It appears to be a lodash issue.
Further more, NPM output: Requested url: /api/options Error: ReferenceError: _ is not defined

**Comment by operatino** [comment]
Hi,

Sorry for the misleading, seems like we missed this line in the docs example:

```
var _ = require('lodash');
module.exports = {
  ...
}
```

Could you please check this out and report back if it helped?
