### ISSUE TITLE
Ability to access Images in a specific folder

### ISSUE THREAD

**Issue by custa1200** [sourcejs/Source#217]
I am placing my images for the style guide in a folder called "/images" at the root of the SourceJS site, but I can't seem to access them using the CSS files within the Spec. They just 404, is there something I have to do in config to allow the grabbing of static images? Is this an Express environment problem within SourceJS?

**Comment by ndelangen** [comment]
I've added custom routes like this:  
*I'm using sourcejs as an npm module*

1. Add a folder named `core` in the root of your project
2. Add a file named `routes.js`
3. Write something like this in that file:
```js
'use strict';

var path = require('path');
var express = require('express');

/**
* Add /assets to static routes
*/
global.app.use('/assets', express.static(path.join(global.userPath, 'assets')));
```

This worked for me. Perhaps there are better ways, I think I got to this solution by peaking at https://github.com/sourcejs/Source/blob/0.6.0-dev/core/routes/redirects.js

**Comment by operatino** [comment]
By default absolute URL's should lead to user root folder, I'll check what might happen with this.

**Comment by custa1200** [comment]
Can't get either to work in 0.6.0, I did change the snippet above to be :
```javascript
global.app.use('/images', express.static(path.join(global.userPath, 'images')));
```
to fit my structure of images being at the root of my site.

**Comment by operatino** [comment]
Seems like it's a bug of `0.6.0`, I'll check it out.

**Comment by custa1200** [comment]
Sorry guys, I think I may have sent people in circles on this one. Looks like the export from sketch had a space at the start of the name. :( @operatino did you want me to close it?

**Comment by operatino** [comment]
@custa1200 so there's no bug, and image is available by absolute url from `user` folder?

**Comment by custa1200** [comment]
Yup I was able to get to it after I removed the leading space the image file had gotten without me realising.
