### ISSUE TITLE
Test release with isolated JavaScript used in SourceJS UI

### ISSUE THREAD

**Issue by operatino** [sourcejs/Source#220]
I’ve released the first alpha version of JS isolation under `0.6.0-isolated-js.0` tag. This is the last big feature to polish before 0.6.0 release, so if somebody could test it around, it will help a lot. 

Now UI code of SourceJS (almost) does not expose any globals except `window.sourcejs`. You can use your own requirejs/jquery and etc, without a fear to interfier with engine code (#204 and others).

![image](http://d.pr/i/PXqM+)

To install it, update the SourceJS dep - `npm i sourcejs@0.6.0-isolated-js.0`. Any feedback and bug report welcome in this issue. The change should be backward compatible, and all the found conflicts will be fixed before merging into `0.6.0-dev`

CAUTION: External plugins with client-side code are still not supported, but I plan to implement backward compatibility later this week.

**Comment by operatino** [comment]
Already merged into `0.6.0-dev`  #221, and available in the new nightly build `0.6.0-nightly.6`.

**Comment by custa1200** [comment]
Big step mate. Awesome work.

**Comment by ndelangen** [comment]
I just updated from `0.6.0-nightly.5` to `0.6.0-nightly.6`.  😎

**Comment by custa1200** [comment]
Just updated mine to nightly.6 too.

**Comment by ndelangen** [comment]
I've merged it into my dev branch and have been working with it for a fair bit. 0 issues!

**Comment by operatino** [comment]
Alright, considered stable then!
