### ISSUE TITLE
Issues doing npm install

### ISSUE THREAD

**Issue by custa1200** [sourcejs/Source#231]
<img width="944" alt="screen shot 2016-06-02 at 12 11 09 pm" src="https://cloud.githubusercontent.com/assets/161224/15731822/39b6556c-28bb-11e6-9a23-ccf85751fc63.png">

When I try to do an npm install on a new machine on the semi corporate network I get these fails? Maybe they are blocking things using the git protocol? Is this something that could be change to improve the chances of grabbing source on every network?

**Comment by operatino** [comment]
Hi,

I've saw the same issue with multiple projects lately, seems like a temporary GitHub issue. Even after getting those errors everything was installed and working though. Do you experience problems with running SourceJS aster seeing those error?

If the problem will repeat, I'll need to investigate what happened and probably I'll be ready to move deps back to npm.

**Comment by operatino** [comment]
I see problems are not occurring anymore, so closing for now.
