### ISSUE TITLE
process.env.PORT - Non-numeric values

### ISSUE THREAD

**Issue by Alanoll** [sourcejs/Source#244]
While researching how to do #243 I noticed that SourceJS is performing a parseInt on the **process.env.PORT** value in [changeset](https://github.com/sourcejs/Source/pull/242/commits/9a08615649a474c201238723e03b020b50092f43).

According to the **http.listen** documentation, the PORT could also be a socket or a named pipe. Doing a parseInt, causes a NaN value to be stored.

**Comment by Alanoll** [comment]
I ran into this issue attempting to use **iisnode** which does end up using a named pipe from the out of process execution of node.

Removing the parseInt got that working.

**Comment by Alanoll** [comment]
@operatino 
Does heroku always pass the value by number? Is that why the parseInt was added?

**Comment by operatino** [comment]
Env variables are always passes as string, so only way is to separate passed settings and env check and do different transforms. Or just if not bool, then parseInt this param.

**Comment by Alanoll** [comment]
`if (commander.port) global.opts.core.server.port = parseInt(commander.port);

if (process.env.PORT) {
    global.opts.core.server.port = parseInt(process.env.PORT);
    console.log('Using defined app PORT from environment variable: ' + process.env.PORT);
}`

So here's the blurb of code (line 62 or so of app.js). I was curious if there was a need to have the value as an number. **http.listen** supports other values like sockets/pipes which are not numbers. 

Does **heroku** have a requirement for the input to be a number or just following the pattern of the original **commander.port** logic?

Seems like we could either remove the parseInt entirely or add some form of a check for NaN after the parse, and inspect the passed value further (though then we'd get into OS specific naming for sockets/pipes).

**Comment by operatino** [comment]
Small test shown that indeed, express `app.listen` could accept string, so we can just remove `pareseInt`.
