### ISSUE TITLE
Error when try install package

### ISSUE THREAD

**Issue by webmarkelov** [sourcejs/Source#246]
Hi! i am try install package but get error 
```
package v.0.5.6 
car: os x 10.11.6
node v.7.4.0
npm v.4.0.5
```
```
/Users/osx/Websites/Docker/www/sitename/node_modules/contextify: Command failed.
Exit code: 1
...
```
I try use the recommendation https://github.com/sourcejs/Source/issues/180 but get other error

version package sourcejs@0.5.6-no-jsdom perfectly work

**Comment by operatino** [comment]
HI @webmarkelov,

Similar to other issue answered, till `0.6.0-dev` we had an unstable dependency for Windows OS, using `0.6.0-nightly.7` will fix your issue.
