### ISSUE TITLE
Проблема с dom

### ISSUE THREAD

**Issue by webmarkelov** [sourcejs/Source#247]
```
package 0.5.6-no-jsdom
node v.7.4.0
npm v.4.0.5
```
Привет! при составлении документации я столкнулся с такой проблемой что пакет [perfect-scrollbar ](https://github.com/noraesae/perfect-scrollbar) не правильно работает  в source.js так как в dev все работает правильно, начал дебажить и увидел что проблема в том что данный модуль не может рассчитать высоту блока (0px) и собственно по этому не правильно работает, мой бандл примерно выглядит так и подключается в конце спеки

``` javascript

(function ($) {
    $(document).ready(function () {
           let Ps = require('perfect-scrollbar');
           [].forEach.call(document.querySelectorAll('.test-block'), el => {
           Ps.initialize(el);
    });
})(jQuery);
```
если выставить таймер в секунду в момент инициализации он отработает правильно но меня не устраивает такой вариант.

**Comment by operatino** [comment]
Hi @webmarkelov,

Sorry for taking so long to reply, been super busy with job change recently. Also sorry for answering in English, but it's better to keep it international.

Till latest changes in `0.6.0-dev`, people had similar issues from time to time with JS conflicts cause by external libraries. In the current dev branch we've implemented a complete isolation of SourceJS dependencies, please use `sourcejs@0.6.0-nightly.7` to try fixing the issue.
