### ISSUE TITLE
Migrate to Github from localhost

### ISSUE THREAD

**Issue by 8man-Jennifer** [sourcejs/Source#248]
Just finished localhostet Styleguide for Websapp company. How do I migrate it to Github? .gitignore has /user how do I get around this?

**Comment by operatino** [comment]
Hi Jenifer,

I've answered your question in our Gitter chat https://gitter.im/sourcejs/Source?at=594baf575bf0bef94cd0e3ea

Cheers

**Comment by 8man-Jennifer** [comment]
Thanks Robert

Von: Robert Haritonov [mailto:notifications@github.com]
Gesendet: Donnerstag, 22. Juni 2017 13:52
An: sourcejs/Source <Source@noreply.github.com>
Cc: Jennifer Simonds <J.Simonds@protected-networks.com>; Author <author@noreply.github.com>
Betreff: Re: [sourcejs/Source] Migrate to Github from localhost (#248)


Hi Jenifer,

I've answered your question in our Gitter chat https://gitter.im/sourcejs/Source?at=594baf575bf0bef94cd0e3ea

Cheers
