### ISSUE TITLE
Redirect from host shortlink to localhost:8080 on Windows

### ISSUE THREAD

**Issue by XOP** [sourcejs/Source#26]
Redirecting from host shortlink, say, 'source' to localhost:8080 can be perfomed by the following command:
```
netsh interface portproxy add v4tov4 listenport=80 listenaddress=127.0.0.1 connectport=8080 connectaddress=YOUR_LOCAL_ADDRESS
```

**Comment by operatino** [comment]
Thank for the tip, very useful! I'll close this issue, but leave in FAQ section.
