### ISSUE TITLE
Using Source as Skins viewer 

### ISSUE THREAD

**Issue by ashmigelski** [sourcejs/Source#59]
Source works nice when you have one CSS (main product styles) and want to apply it different HTML elements, thanks for this :+1:

Our main product has different skins (logos, css) for different customers and i want to use source for skins system  documentation.

First I'm want to solve such problem - i have one HTML code and want to apply different CSS skins to it.  Idea is to show how template page (core/view/skins.ejs) looks with different styles (/skins/ sub folders). 
To demonstrate i created simple project https://github.com/ashmigelski/sourcejs-skins-viewer compatible with current v.0.4.0 branch. It uses very straightforward logic - every skin is a spec with info.json and
index.src inside.
Any tips or suggestions how to make it easier and more efficient? Thanks

**Comment by operatino** [comment]
Documentation and examples of plugins and middleware http://sourcejs.com/docs/api/plugins
