### ISSUE TITLE
Clarify: Add browser-sync injection

### ISSUE THREAD

**Issue by Leikam** [sourcejs/Source#85]
Inject browser-sync script on clarified page, that allow connect to remote chrome-like debugger.

**Comment by operatino** [comment]
Maybe it's better to use separate proxy server for this? As I remember, browser sync must have it.

We need to keep core unopinioned, adding specific tools like this to plugins and external config recipes.

It could be easily done with SourceJS Middleware Plugin for all specs.

**Comment by Leikam** [comment]
Yes, I agree that it should be done on the middleware level. Common reason make this plugin is to provide more convenient way for CSS injection without separate page (proxied by bsync own static-server), but using all benefit of Sourcejs.

**Comment by operatino** [comment]
And here comes the plugin https://github.com/sourcejs/sourcejs-contrib-browser-sync
