### ISSUE TITLE
Search improvements

### ISSUE THREAD

**Issue by XOP** [sourcejs/Source#93]
Search should be operated in two modes
- default minimalistic (searches through titles and tags)
- full, separarated instrument with user filters (involves previews and search results based on full document, and it should consider popular word mistakes as well - "clever input")

It should be very transparent task to get to full search page. Also, consider making it the entry point to the Source (may be configured by user modes)

**Comment by operatino** [comment]
We can add `description` field for indexing in minimalistic search as well, and even probably add some smart typo fixing. With current search possibilities plus few improvements on top, we will cover all needs for searching even through big components library. 

I agree that filters could be useful, and we're already planing to separate catalog searching, to limit the scope. But complex filter system, and full text search is really an overkill for components libraries. We don't want to rebuild Google in SourceJS, maybe you can check out how to connect Google search services to your library?

This kind of extended search with more complex filters could be done as a plugin (same as Styles), and from `user/core/app.js` you can redefine root routing, so main page will be taken from other places.
