### ISSUE TITLE
Replace JSdom with Cheerio

### ISSUE THREAD

**Issue by operatino** [sourcejs/Source#99]
To achieve more pleasant experience of SourceJS installation and to do stuff more efficiently in terms of performance, we chose migration to https://github.com/cheeriojs/cheerio from JSdom.

Current modules that needs to be refactored:
* Clarify - uses JSdom to run universal spec parsing script. Will be most difficult to rewrite
* read.js middleware - adds some runtime processing of Specs before sending the response, could be easily rewritten to use cheerio
* index.md support - will use cheerio from first release

**Comment by operatino** [comment]
Index.md support already uses cheerio #100

**Comment by tcorral** [comment]
Could you @operatino assign me this issue, please? I could not do it by myself.

**Comment by operatino** [comment]
Done! I've also added you to contributors groups, so you now should be able to interact with tasks. If you chose this task to solve, come over to discuss the details.

Or you can first jump in and see how it works by yourself, here are the files to check:

`sourcejs/core/middleware/clarify.js` - gets the spec page, runs client side parser (`window.SourceGetSections`) and returns an object with HTML parts. `SourceGetSections` is located in `source/assets/js/modules/sectionsParser.js`, and should be runnable on server side.
`sourcejs/core/middleware/wrap.js` - this is easier, it's just searching for `<head>` tag, and if there is and element for that, it passes it's contents to EJS templating engine

Just for SourceJS and when you're ready, create PR to get feedback, or just catch me in the office.

**Comment by operatino** [comment]
Branch with temp JSDom cleanup - 0.5.3-bb. Clarify feature is turned off there, as a temp solution. And we also need to re-check how pages with duplicated head are rendered.

**Comment by operatino** [comment]
I replaced JSDom with cheerio in `operatino/no-jsdom-in-wrap` branch. Spec is now loading much faster as well, keeping `<head>` section feature, and HTML normalization, same as we had in JSDom.

But I'm planning to remove all those custom processing from `wrap.js` in 0.6.0, moving them to plugins. Most probably I will create two small plugins based on cheerio and jsdom.

**Comment by tcorral** [comment]
Hi @operatino . Could you check why the tests are not working in master branch? I am trying to execute the test to know if the changes are ok and work as expected but seems that something is broken in master.

**Comment by operatino** [comment]
@tcorral, you need to run the app first, and then trigger the tests, they should be passing. In 0.5.3 I already updated `npm test`, so it automatically runs the app before the tests.

**Comment by tcorral** [comment]
I have tried to make a clean checkout of 0.5.3-dev branch and execute the npm test but I get this error 'ENOENT, no such file or directory '/Users/tomascorralcasas/WebStormProjects/Source/user'

**Comment by operatino** [comment]
Just follow the install instructions to get right SourceJS set-up http://sourcejs.com/docs/base/#install, or in your case, you will need to just clone this repo in `sourcejs/user` folder https://github.com/sourcejs/init.

BTW, 0.5.3 is already released and 0.5.3-dev branch is now deleted, I have left only freezed tag for it.

**Comment by operatino** [comment]
Reach me through Skype haritonov.r or email r@rhr.me for more details.

**Comment by tcorral** [comment]
ok


2015-05-31 2:07 GMT-07:00 Robert Haritonov <notifications@github.com>:

**Comment by operatino** [comment]
Done
